services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  TYPO3\CMS\Fluid\:
    resource: '../Classes/*'
    # glob for services that have been previously available as
    # container entries and have been removed in the meantime
    # (e.g. because factories are to be used instead)
    exclude: '../Classes/{Core/Rendering/RenderingContext.php}'

  # TemplateView and StandaloneView have $context = null, symfony auto-injects in that case,
  # extbase did not, force passing `null`
  TYPO3\CMS\Fluid\View\StandaloneView:
    public: true
    shared: false
    arguments:
      $context: null
  TYPO3\CMS\Fluid\View\TemplateView:
    public: true
    shared: false
    arguments:
      $context: null

  cache.fluid_template:
    class: TYPO3\CMS\Core\Cache\Frontend\FrontendInterface
    factory: ['@TYPO3\CMS\Core\Cache\CacheManager', 'getCache']
    arguments: ['fluid_template']

  # Classes of base package
  TYPO3Fluid\Fluid\Core\Parser\TemplateProcessor\EscapingModifierTemplateProcessor:
    public: true
    shared: false
  TYPO3Fluid\Fluid\Core\Parser\TemplateProcessor\PassthroughSourceModifierTemplateProcessor:
    public: true
    shared: false
  TYPO3Fluid\Fluid\Core\Parser\TemplateProcessor\NamespaceDetectionTemplateProcessor:
    public: true
    shared: false

  # VH's of base package
  TYPO3Fluid\Fluid\ViewHelpers\Cache\DisableViewHelper:
    tags: [ 'fluid.viewhelper' ]
    autowire: false
  TYPO3Fluid\Fluid\ViewHelpers\Cache\StaticViewHelper:
    tags: [ 'fluid.viewhelper' ]
    autowire: false
  TYPO3Fluid\Fluid\ViewHelpers\Cache\WarmupViewHelper:
    tags: [ 'fluid.viewhelper' ]
    autowire: false
  TYPO3Fluid\Fluid\ViewHelpers\Format\CdataViewHelper:
    tags: [ 'fluid.viewhelper' ]
    autowire: false
  TYPO3Fluid\Fluid\ViewHelpers\Format\HtmlspecialcharsViewHelper:
    tags: [ 'fluid.viewhelper' ]
    autowire: false
  TYPO3Fluid\Fluid\ViewHelpers\Format\PrintfViewHelper:
    tags: [ 'fluid.viewhelper' ]
    autowire: false
  TYPO3Fluid\Fluid\ViewHelpers\Format\RawViewHelper:
    tags: [ 'fluid.viewhelper' ]
    autowire: false
  TYPO3Fluid\Fluid\ViewHelpers\AliasViewHelper:
    tags: [ 'fluid.viewhelper' ]
    autowire: false
  TYPO3Fluid\Fluid\ViewHelpers\CaseViewHelper:
    tags: [ 'fluid.viewhelper' ]
    autowire: false
  TYPO3Fluid\Fluid\ViewHelpers\CommentViewHelper:
    tags: [ 'fluid.viewhelper' ]
    autowire: false
  TYPO3Fluid\Fluid\ViewHelpers\CountViewHelper:
    tags: [ 'fluid.viewhelper' ]
    autowire: false
  TYPO3Fluid\Fluid\ViewHelpers\CycleViewHelper:
    tags: [ 'fluid.viewhelper' ]
    autowire: false
  TYPO3Fluid\Fluid\ViewHelpers\DebugViewHelper:
    tags: [ 'fluid.viewhelper' ]
    autowire: false
  TYPO3Fluid\Fluid\ViewHelpers\DefaultCaseViewHelper:
    tags: [ 'fluid.viewhelper' ]
    autowire: false
  TYPO3Fluid\Fluid\ViewHelpers\ElseViewHelper:
    tags: [ 'fluid.viewhelper' ]
    autowire: false
  TYPO3Fluid\Fluid\ViewHelpers\ForViewHelper:
    tags: [ 'fluid.viewhelper' ]
    autowire: false
  TYPO3Fluid\Fluid\ViewHelpers\GroupedForViewHelper:
    tags: [ 'fluid.viewhelper' ]
    autowire: false
  TYPO3Fluid\Fluid\ViewHelpers\IfViewHelper:
    tags: [ 'fluid.viewhelper' ]
    autowire: false
  TYPO3Fluid\Fluid\ViewHelpers\InlineViewHelper:
    tags: [ 'fluid.viewhelper' ]
    autowire: false
  TYPO3Fluid\Fluid\ViewHelpers\LayoutViewHelper:
    tags: [ 'fluid.viewhelper' ]
    autowire: false
  TYPO3Fluid\Fluid\ViewHelpers\OrViewHelper:
    tags: [ 'fluid.viewhelper' ]
    autowire: false
  TYPO3Fluid\Fluid\ViewHelpers\RenderViewHelper:
    tags: [ 'fluid.viewhelper' ]
    autowire: false
  TYPO3Fluid\Fluid\ViewHelpers\SectionViewHelper:
    tags: [ 'fluid.viewhelper' ]
    autowire: false
  TYPO3Fluid\Fluid\ViewHelpers\SpacelessViewHelper:
    tags: [ 'fluid.viewhelper' ]
    autowire: false
  TYPO3Fluid\Fluid\ViewHelpers\SwitchViewHelper:
    tags: [ 'fluid.viewhelper' ]
    autowire: false
  TYPO3Fluid\Fluid\ViewHelpers\ThenViewHelper:
    tags: [ 'fluid.viewhelper' ]
    autowire: false
  TYPO3Fluid\Fluid\ViewHelpers\VariableViewHelper:
    tags: [ 'fluid.viewhelper' ]
    autowire: false
