services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  TYPO3\CMS\Fluid\:
    resource: '../Classes/*'

  # Templateview has $context = null, symfony auto-injects in that case,
  # extbase did not, force passing `null`
  TYPO3\CMS\Fluid\View\TemplateView:
    arguments:
      $context: null

  cache.fluid_template:
    class: TYPO3\CMS\Core\Cache\Frontend\FrontendInterface
    factory: ['@TYPO3\CMS\Core\Cache\CacheManager', 'getCache']
    arguments: ['fluid_template']
